drop database if exists springprueba_modelo;
create database springprueba_modelo;
use springprueba_modelo;

drop table if exists PROFESOR_MODULO;
drop table if exists MODULO;
drop table if exists EMAIL;
drop table if exists PROFESOR;

CREATE TABLE PROFESOR
(
   ID_PROFESOR INT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   APELLIDOS VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_PROFESOR)
);

CREATE TABLE EMAIL
(
   ID_EMAIL INT NOT NULL AUTO_INCREMENT,
   DIRECCION_EMAIL VARCHAR (40) NOT NULL UNIQUE,
   ID_PROFESOR INT NOT NULL,
   PRIMARY KEY (ID_EMAIL),
   CONSTRAINT FK_EMAIL_PROFESOR FOREIGN KEY (ID_EMAIL) REFERENCES PROFESOR (ID_PROFESOR)
);

CREATE TABLE MODULO
(
   ID_MODULO INT NOT NULL AUTO_INCREMENT,
   NOMBRE_MODULO VARCHAR (40) NOT NULL UNIQUE,
   PRIMARY KEY (ID_MODULO)
);


CREATE TABLE PROFESOR_MODULO
(
   ID_PROFESOR INT NOT NULL,
   ID_MODULO INT NOT NULL,
   PRIMARY KEY
   (
      ID_PROFESOR,
      ID_MODULO
   ),
   CONSTRAINT FK_PROFESOR_MODULO_1 FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR (ID_PROFESOR) ON DELETE CASCADE,
   CONSTRAINT FK_PROFESOR_MODULO_2 FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO)
);